<template>
    <div class="d-flex justify-center">
        <VCard class="ma-5 d-flex flex-column justify-center align-center" max-width="800px">
            <VAvatar :image="avatarSrc" size="80" />
            <VCardTitle class="text-center font-bold">I am Avei</VCardTitle>

            <VCardItem>
                <VBtn class="mx-1" icon="mdi-github" density="compact" href="https://github.com/Avei20" />
                <VBtn class="mx-1" icon="mdi-linkedin" density="compact" href="https://www.linkedin.com/in/avei" />
                <VBtn class="mx-1" icon="mdi-twitter" density="compact" href="https://twitter.com/avei__" />
                <VBtn class="mx-1" icon="mdi-instagram" density="compact" href="https://instagram.com/avei___" />
            </VCardItem>

            <VCardText class="text-center py-2">
                Here are a list of my production work which can be accessed by in my
                Github account. Feel free to contact me for collaboration about AI,
                Machine Learning and Web Development Projects.
            </VCardText>

            <VCardItem class="w-100">
                <VDivider />
                <VExpansionPanels class="w-100 px-4">
                    <VExpansionPanel class="ma-2" title="Gemini Chat" color="primary">
                        <VExpansionPanelText>
                            <span>Self-made AI chatbot using Gemini API with websocket connection into
                                <a href="https://nest.avei.ovh/docs">Avei Nest.js</a> backend</span>
                            <div class="d-flex align-center justify-item-between pt-3">
                                <VBtn class="w-fit mx-3" icon="mdi-github" density="compact" href="https://github.com/Avei20/avei-nuxt" />
                                <a href="/chat" class="text-decoration-none">
                                    <VBtn class="w-fit mx-3" color="primary">Try It!</VBtn>
                                </a>
                            </div>
                        </VExpansionPanelText>
                    </VExpansionPanel>

                    <VExpansionPanel class="ma-2" title="Knowledge Graph" color="primary">
                        <VExpansionPanelText>
                            <span>
                                Knowledge Graph is a graph database using neo4j. The
                                graph is generated by injecting LLM response into
                                the database and visualize using sigma.js.
                            </span>
                            <div class="d-flex align-center justify-item-between pt-3">
                                <VBtn class="w-fit mx-3" icon="mdi-github" density="compact" href="https://github.com/Avei20/avei-nuxt" />
                                <a href="/graph" class="text-decoration-none">
                                    <VBtn class="w-fit mx-3" color="primary">Try it!</VBtn>
                                </a>
                            </div>
                        </VExpansionPanelText>
                    </VExpansionPanel>

                    <VExpansionPanel class="ma-2" title="Selfhosted Excalidraw" color="primary">
                        <VExpansionPanelText>
                            <span>
                                Excalidraw is a whiteboard tool that let you draw
                                and collaborate with your team. This is a selfhosted
                                version of Excalidraw.
                            </span>
                            <div class="d-flex align-center justify-item-between pt-3">
                                <VBtn class="w-fit mx-3" icon="mdi-github" density="compact" href="https://github.com/Avei20/avei-draw" />
                                <VBtn class="w-fit mx-3" color="primary" href="https://draw.avei.ovh">Try it!</VBtn>
                            </div>
                        </VExpansionPanelText>
                    </VExpansionPanel>

                    <VExpansionPanel class="ma-2" title="Nest.js API" color="primary">
                        <VExpansionPanelText>
                            <span>
                                Nest.js API is a backend API for my production work.
                                It is a REST API with Swagger Docs.
                            </span>
                            <div class="d-flex align-center justify-item-between pt-3">
                                <VBtn class="w-fit mx-3" icon="mdi-github" density="compact" href="https://github.com/Avei20/avei-nest" />
                                <VBtn class="w-fit mx-3" color="primary" href="https://nest.avei.ovh/docs">Try it!</VBtn>
                            </div>
                        </VExpansionPanelText>
                    </VExpansionPanel>

                    <VExpansionPanel class="ma-2" title="Echo API" color="primary">
                        <VExpansionPanelText>
                            <span>
                                Echo API is a backend API for my production work. It
                                is a REST API with Swagger Docs.
                            </span>
                            <div class="d-flex align-center justify-item-between pt-3">
                                <VBtn class="w-fit mx-3" icon="mdi-github" density="compact" href="https://github.com/Avei20/avei-echo" />
                                <VBtn class="w-fit mx-3" color="primary" href="https://echo.avei.ovh/">Try it!</VBtn>
                            </div>
                        </VExpansionPanelText>
                    </VExpansionPanel>

                    <VExpansionPanel class="ma-2" title="Elysia API" color="primary">
                        <VExpansionPanelText>
                            <span>
                                Elysia API is a backend API for my production work.
                                It is a REST API with Swagger Docs.
                            </span>
                            <div class="d-flex align-center justify-item-between pt-3">
                                <VBtn class="w-fit mx-3" icon="mdi-github" density="compact" href="https://github.com/Avei20/avei-elysia" />
                                <VBtn class="w-fit mx-3" color="primary" href="https://elysia.avei.ovh/">Try it!</VBtn>
                            </div>
                        </VExpansionPanelText>
                    </VExpansionPanel>
                </VExpansionPanels>
            </VCardItem>

            <VCardText>Fell free to give a feedback and hate comment here. Thanks. Your identity is anonymous.</VCardText>

            <FeedbackForm />
        </VCard>
    </div>
</template>

<script setup lang="ts">
import FeedbackForm from "./FeedbackForm.vue";

defineProps<{ avatarSrc: string }>();
</script>
